# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.14"
  amd64: "ghcr.io/home-assistant/amd64-base:3.14"
  armhf: "ghcr.io/home-assistant/armhf-base:3.14"
  armv7: "ghcr.io/home-assistant/armv7-base:3.14"
  i386: "ghcr.io/home-assistant/i386-base:3.14"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: lego"
  org.opencontainers.image.description: "Let's Encrypt client and ACME library written in Go."
  org.opencontainers.image.source: "https://github.com/via-justa/via-justa-home-assistant-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  LEGO_VERSION: v4.5.3