# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Lego
version: "0.5.0"
stage: experimental
slug: lego
description: Let's Encrypt client and ACME library written in Go.
url: "https://github.com/via-justa/go-acme-lego-addon/tree/main/lego"
image: ghcr.io/via-justa/{arch}-lego
hassio_api: true
hassio_role: manager
homeassistant_api: true
map:
  - ssl:rw
  - share
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
options:
  provider: ""
  domains: []
  email: ""
  restart: true
  env_vars:
    - name: ""
      value: ""
schema:
  provider: str?
  domains: 
    - str
  email: str
  restart: bool
  check_time: match(^\d\d\:\d\d$)?
  env_vars:
    - name: match(^([A-Z0-9_])+$)
      value: str
  challenge: list(dns|http)?
  addons:
    - str?
  renew_threshold: int?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  # Development option
  dev: bool?
ports:
  80/tcp: 8091
ports_description:
  80/tcp: Only needed for http challenge
